server:
  port: 8080

spring:
  application:
    name: street-scout
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

aws:
  s3:
    access:
      key: ${AWS_ACCESS_KEY_ID}
    secret:
      key: ${AWS_SECRET_ACCESS_KEY}